### ISSUE TITLE
when reported `401 Bad credentials`, can not reopen once credential process

### ISSUE THREAD

**Issue by xingangshi** [xjh22222228/boomb#3]
### Version
1.8.0

### Reproduction link
[https://boomb.cn/login](https://boomb.cn/login)

### Steps to reproduce
1. click the loging icon and login  2. select one of an organization to Grant 3. can't see the repo in the selected organization 4. delete Authorize in personal settings 5. can't get the page of Authorize

### What is expected?
fixed the bug

### What is actually happening?
can not reopen once credential process

**Comment by xjh22222228** [comment]
Can GIF playback steps be recorded.

**Comment by xingangshi** [comment]
> Can GIF playback steps be recorded.

I can not repeat the bug, now, when I open https://boomb.cn, is just show me "401Bad credentials" 
[the bug screenshort](https://wx4.sinaimg.cn/large/007lcHJHgy1gyhu9x64iwj30gz0fkdgf.jpg)

**Comment by xjh22222228** [comment]
image not accessible.

**Comment by xingangshi** [comment]
> image not accessible.

try to copy it then paste the url into a browser.
