### ISSUE TITLE
每次访问 Boomb 都要求 gitee 重新授权登录

### ISSUE THREAD

**Issue by nojsja** [xjh22222228/boomb#4]
### What problem does this feature solve?
每次访问 Boomb 都要求 gitee 重新授权登录。

### What does the proposed API look like?
希望能增加登录记忆，不用每次都要授权一遍，而可以直接进去页面。

**Comment by xjh22222228** [comment]
默认会自动登入的。

**Comment by nojsja** [comment]
刚看又可以了，之前几乎隔两三天天就要登录一下，我先关了
